/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** login */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "cto",
                     *       "password": "password"
                     *     }
                     */
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3Nzk2OTI5OTcsImV4cCI6MTc3OTk1MjE5NywibmJmIjoxNzc5NjkyOTk3LCJqdGkiOiJYT0VEbDlWa25kTUM1OWVRIiwic3ViIjoiMiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.LLuha8bffm4TcbpzaGMOWDmRUYCI2lstCHoFyzxBC6Y",
                         *         "user": {
                         *           "id": 2,
                         *           "first_name": "Accountant",
                         *           "last_name": "User",
                         *           "username": "accountant",
                         *           "status": 1,
                         *           "department_id": 1,
                         *           "email_verified_at": null,
                         *           "deleted_at": null,
                         *           "created_at": "2026-05-25T07:09:25.000000Z",
                         *           "updated_at": "2026-05-25T07:09:25.000000Z",
                         *           "role": "Accountant"
                         *         }
                         *       },
                         *       "message": "تم تسجيل الدخول بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                token: string;
                                user: {
                                    id: number;
                                    first_name: string;
                                    last_name: string;
                                    username: string;
                                    status: number;
                                    department_id: number;
                                    email_verified_at: null;
                                    deleted_at: null;
                                    created_at: string;
                                    updated_at: string;
                                    /** @enum {string} */
                                    role: "Accountant" | "CTO" | "IT";
                                    user_name: string;
                                    email: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** logout */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": null,
                         *       "message": "تم تسجيل الخروج بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: null;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** me */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "user": {
                         *           "id": 2,
                         *           "first_name": "Accountant",
                         *           "last_name": "User",
                         *           "username": "accountant",
                         *           "status": 1,
                         *           "department_id": 1,
                         *           "email_verified_at": null,
                         *           "deleted_at": null,
                         *           "created_at": "2026-05-25T07:08:26.000000Z",
                         *           "updated_at": "2026-05-25T07:08:26.000000Z",
                         *           "role": "Accountant"
                         *         }
                         *       },
                         *       "message": "تم الحصول على البيانات بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                user: {
                                    id: number;
                                    first_name: string;
                                    last_name: string;
                                    username: string;
                                    status: number;
                                    department_id: number;
                                    email_verified_at: null;
                                    deleted_at: null;
                                    created_at: string;
                                    updated_at: string;
                                    role: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role :CTO
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "current_page": 1,
                         *         "data": [
                         *           {
                         *             "id": 1,
                         *             "name": "ali abdelhaq",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "CTO",
                         *             "username": "cto"
                         *           },
                         *           {
                         *             "id": 2,
                         *             "name": "Accountant User",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "Accountant",
                         *             "username": "accountant"
                         *           },
                         *           {
                         *             "id": 3,
                         *             "name": "IT User",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "IT",
                         *             "username": "it"
                         *           },
                         *           {
                         *             "id": 4,
                         *             "name": "John Doe",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "IT",
                         *             "username": "john"
                         *           },
                         *           {
                         *             "id": 5,
                         *             "name": "Linus Lynn",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "CTO",
                         *             "username": "sypuqusur"
                         *           },
                         *           {
                         *             "id": 6,
                         *             "name": "Callum Donaldson",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "CTO",
                         *             "username": "tovyx"
                         *           },
                         *           {
                         *             "id": 7,
                         *             "name": "ali abed",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "CTO",
                         *             "username": "aliabed"
                         *           },
                         *           {
                         *             "id": 8,
                         *             "name": "Taylor Mckay",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "CTO",
                         *             "username": "pahyhub"
                         *           },
                         *           {
                         *             "id": 9,
                         *             "name": "Fletcher Snow",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "Accountant",
                         *             "username": "pubofeqofy"
                         *           },
                         *           {
                         *             "id": 10,
                         *             "name": "Wyoming Holland",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "IT",
                         *             "username": "fawot"
                         *           },
                         *           {
                         *             "id": 11,
                         *             "name": "محمد ماهر",
                         *             "department": "Raqqam",
                         *             "status": 1,
                         *             "role": "IT",
                         *             "username": "maher"
                         *           }
                         *         ],
                         *         "first_page_url": "http://172.20.2.65:8000/api/users?page=1",
                         *         "from": 1,
                         *         "last_page": 1,
                         *         "last_page_url": "http://172.20.2.65:8000/api/users?page=1",
                         *         "links": [
                         *           {
                         *             "url": null,
                         *             "label": "&laquo; Previous",
                         *             "page": null,
                         *             "active": false
                         *           },
                         *           {
                         *             "url": "http://172.20.2.65:8000/api/users?page=1",
                         *             "label": "1",
                         *             "page": 1,
                         *             "active": true
                         *           },
                         *           {
                         *             "url": null,
                         *             "label": "Next &raquo;",
                         *             "page": null,
                         *             "active": false
                         *           }
                         *         ],
                         *         "next_page_url": null,
                         *         "path": "http://172.20.2.65:8000/api/users",
                         *         "per_page": 15,
                         *         "prev_page_url": null,
                         *         "to": 11,
                         *         "total": 11
                         *       },
                         *       "message": "تم استرجاع المستخدمين بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                current_page: number;
                                data: {
                                    id: number;
                                    name: string;
                                    department: string;
                                    status: number;
                                    role: string;
                                    username: string;
                                }[];
                                first_page_url: string;
                                from: number;
                                last_page: number;
                                last_page_url: string;
                                links: {
                                    url: string | null;
                                    label: string;
                                    page: number | null;
                                    active: boolean;
                                }[];
                                next_page_url: null;
                                path: string;
                                per_page: number;
                                prev_page_url: null;
                                to: number;
                                total: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role :CTO
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "first_name": "John",
                     *       "last_name": "Doe",
                     *       "username": "john",
                     *       "password": "Password",
                     *       "password_confirmation": "Password",
                     *       "role": "IT",
                     *       "department_id": 1
                     *     }
                     */
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        username: string;
                        email: string;
                        password: string;
                        password_confirmation: string;
                        role: string;
                        department_id: number;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "first_name": "John",
                         *         "last_name": "Doe",
                         *         "username": "john",
                         *         "department_id": 1,
                         *         "updated_at": "2026-05-25T07:15:47.000000Z",
                         *         "created_at": "2026-05-25T07:15:47.000000Z",
                         *         "id": 4,
                         *         "role": "IT"
                         *       },
                         *       "message": "تم إنشاء المستخدم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                first_name: string;
                                last_name: string;
                                username: string;
                                department_id: number;
                                updated_at: string;
                                created_at: string;
                                id: number;
                                role: string;
                                email: string;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show
         * @description Role :CTO
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 1 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "first_name": "CTO",
                         *         "last_name": "User",
                         *         "username": "cto",
                         *         "status": 1,
                         *         "department_id": 1,
                         *         "email": "cto@example.com",
                         *         "email_verified_at": null,
                         *         "deleted_at": null,
                         *         "created_at": "2026-05-21T13:39:41.000000Z",
                         *         "updated_at": "2026-05-21T13:39:41.000000Z",
                         *         "role": "CTO",
                         *         "department": {
                         *           "id": 1,
                         *           "name": "Raqqam"
                         *         }
                         *       },
                         *       "message": "تم استرجاع المستخدم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                first_name: string;
                                last_name: string;
                                username: string;
                                status: number;
                                department_id: number;
                                email: string;
                                email_verified_at: null;
                                deleted_at: null;
                                created_at: string;
                                updated_at: string;
                                role: string;
                                department: {
                                    id: number;
                                    name: string;
                                };
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        /**
         * Update
         * @description Role :CTO
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 11 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name?: string;
                        last_name?: string;
                        username?: string;
                        password?: string;
                        password_confirmation?: string;
                        role?: string;
                        department_id?: number;
                        status?: number;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 4,
                         *         "first_name": "John",
                         *         "last_name": "Doe",
                         *         "username": "john",
                         *         "status": 1,
                         *         "department_id": 1,
                         *         "email_verified_at": null,
                         *         "deleted_at": null,
                         *         "created_at": "2026-05-25T07:15:47.000000Z",
                         *         "updated_at": "2026-05-25T07:15:47.000000Z",
                         *         "role": "IT"
                         *       },
                         *       "message": "تم تحديث المستخدم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                first_name: string;
                                last_name: string;
                                username: string;
                                status: number;
                                department_id: number;
                                email_verified_at: null;
                                deleted_at: null;
                                created_at: string;
                                updated_at: string;
                                role: string;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete
         * @description Role :CTO
         */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 4 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": null,
                         *       "message": "تم حذف المستخدم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: null;
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/toggle-status/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * toggle
         * @description Role :CTO
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 4 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 4,
                         *         "first_name": "John",
                         *         "last_name": "Doe",
                         *         "username": "john",
                         *         "status": false,
                         *         "department_id": 1,
                         *         "email_verified_at": null,
                         *         "deleted_at": null,
                         *         "created_at": "2026-05-25T07:15:47.000000Z",
                         *         "updated_at": "2026-05-25T07:20:27.000000Z",
                         *         "role": "IT"
                         *       },
                         *       "message": "تم تحديث حالة المستخدم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                first_name: string;
                                last_name: string;
                                username: string;
                                status: boolean;
                                department_id: number;
                                email_verified_at: null;
                                deleted_at: null;
                                created_at: string;
                                updated_at: string;
                                role: string;
                                user_name: string;
                                email: string;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role :CTO
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 3,
                         *           "name": "Accountant"
                         *         },
                         *         {
                         *           "id": 1,
                         *           "name": "CTO"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "IT"
                         *         }
                         *       ],
                         *       "message": "تم جلب الصلاحيات بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                            }[];
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role :IT
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "name": "Hessel-Baumbach"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "Shanahan LLC"
                         *         },
                         *         {
                         *           "id": 3,
                         *           "name": "Bashirian and Sons"
                         *         },
                         *         {
                         *           "id": 4,
                         *           "name": "Witting LLC"
                         *         },
                         *         {
                         *           "id": 5,
                         *           "name": "Roberts Inc"
                         *         },
                         *         {
                         *           "id": 6,
                         *           "name": "Streich Ltd"
                         *         },
                         *         {
                         *           "id": 7,
                         *           "name": "Rutherford and Sons"
                         *         },
                         *         {
                         *           "id": 8,
                         *           "name": "D'Amore and Sons"
                         *         },
                         *         {
                         *           "id": 9,
                         *           "name": "Metz Group"
                         *         },
                         *         {
                         *           "id": 10,
                         *           "name": "Grimes, Wolff and Mann"
                         *         }
                         *       ],
                         *       "message": "تم جلب الشركات بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                            }[];
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role :IT
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Zikola"
                     *     }
                     */
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "name": "Zikola",
                         *         "updated_at": "2026-05-23T09:52:16.000000Z",
                         *         "created_at": "2026-05-23T09:52:16.000000Z",
                         *         "id": 11
                         *       },
                         *       "message": "تم إنشاء الشركة بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                name: string;
                                updated_at: string;
                                created_at: string;
                                id: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role:IT
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "name": "Raqqam"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "new department"
                         *         }
                         *       ],
                         *       "message": "تم جلب الأقسام بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                            }[];
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role :IT
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "new department"
                     *     }
                     */
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "name": "new department",
                         *         "updated_at": "2026-05-23T09:54:08.000000Z",
                         *         "created_at": "2026-05-23T09:54:08.000000Z",
                         *         "id": 2
                         *       },
                         *       "message": "تم إنشاء القسم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                name: string;
                                updated_at: string;
                                created_at: string;
                                id: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role :IT
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "name": "sit"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "et"
                         *         },
                         *         {
                         *           "id": 3,
                         *           "name": "et"
                         *         },
                         *         {
                         *           "id": 4,
                         *           "name": "porro"
                         *         },
                         *         {
                         *           "id": 5,
                         *           "name": "quidem"
                         *         },
                         *         {
                         *           "id": 6,
                         *           "name": "numquam"
                         *         },
                         *         {
                         *           "id": 7,
                         *           "name": "sit"
                         *         },
                         *         {
                         *           "id": 8,
                         *           "name": "enim"
                         *         },
                         *         {
                         *           "id": 9,
                         *           "name": "eos"
                         *         },
                         *         {
                         *           "id": 10,
                         *           "name": "in"
                         *         }
                         *       ],
                         *       "message": "تم جلب العناصر بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                            }[];
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role : IT
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Screen"
                     *     }
                     */
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "name": "Screen",
                         *         "updated_at": "2026-05-23T09:50:38.000000Z",
                         *         "created_at": "2026-05-23T09:50:38.000000Z",
                         *         "id": 12
                         *       },
                         *       "message": "تم إنشاء العنصر بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                name: string;
                                updated_at: string;
                                created_at: string;
                                id: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role:Accountant, CTO, IT
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description pending , accepted ,  rejected
                     * @example accepted
                     */
                    "filter[status]"?: string;
                    /** @example 2026-05-23 */
                    "filter[created_at]"?: string;
                    /** @example 10 */
                    paginate?: string;
                };
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "current_page": 1,
                         *         "data": [
                         *           {
                         *             "id": 1,
                         *             "created_at": "2026-05-23T11:10:00.000000Z",
                         *             "total_quantity": 7,
                         *             "status": "pending",
                         *             "updated_at": "2026-05-23T11:10:00.000000Z"
                         *           }
                         *         ],
                         *         "first_page_url": "http://127.0.0.1:8000/api/orders?page=1",
                         *         "from": 1,
                         *         "last_page": 1,
                         *         "last_page_url": "http://127.0.0.1:8000/api/orders?page=1",
                         *         "links": [
                         *           {
                         *             "url": null,
                         *             "label": "&laquo; Previous",
                         *             "page": null,
                         *             "active": false
                         *           },
                         *           {
                         *             "url": "http://127.0.0.1:8000/api/orders?page=1",
                         *             "label": "1",
                         *             "page": 1,
                         *             "active": true
                         *           },
                         *           {
                         *             "url": null,
                         *             "label": "Next &raquo;",
                         *             "page": null,
                         *             "active": false
                         *           }
                         *         ],
                         *         "next_page_url": null,
                         *         "path": "http://127.0.0.1:8000/api/orders",
                         *         "per_page": 15,
                         *         "prev_page_url": null,
                         *         "to": 1,
                         *         "total": 1
                         *       },
                         *       "message": "تم جلب الطلبات بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                current_page: number;
                                data: {
                                    id?: number;
                                    created_at?: string;
                                    total_quantity?: number;
                                    status?: string;
                                    updated_at?: string;
                                }[];
                                first_page_url: string;
                                from: number;
                                last_page: number;
                                last_page_url: string;
                                links: {
                                    url: string | null;
                                    label: string;
                                    page: number | null;
                                    active: boolean;
                                }[];
                                next_page_url: null;
                                path: string;
                                per_page: number;
                                prev_page_url: null;
                                to: number;
                                total: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role:IT
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "item_id": 2,
                     *           "quantity": 5,
                     *           "company_id": 3,
                     *           "department_id": 1,
                     *           "applier_id": 1
                     *         },
                     *         {
                     *           "item_id": 4,
                     *           "quantity": 2,
                     *           "company_id": 2,
                     *           "department_id": 1,
                     *           "applier_id": 1
                     *         }
                     *       ],
                     *       "notes": "new order for software"
                     *     }
                     */
                    "application/json": {
                        items: {
                            item_id: number;
                            quantity: number;
                            company_id: number;
                            department_id: number;
                            applier_id: number;
                        }[];
                        notes: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "user_id": 3,
                         *         "status": "pending",
                         *         "notes": "new order for software",
                         *         "updated_at": "2026-05-23T13:18:57.000000Z",
                         *         "created_at": "2026-05-23T13:18:57.000000Z",
                         *         "id": 1
                         *       },
                         *       "message": "تم إنشاء الطلب بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                user_id: number;
                                status: string;
                                notes: string;
                                updated_at: string;
                                created_at: string;
                                id: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show
         * @description Role : IT ,Accountant,CTO
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 1 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 1,
                         *         "created_at": "2026-05-25T07:17:56.000000Z",
                         *         "order_items": [
                         *           {
                         *             "id": 1,
                         *             "item": "qui",
                         *             "company": "Bashirian and Sons",
                         *             "department": "Raqqam",
                         *             "applier": "Ms. Simone Gislason",
                         *             "quantity": 5
                         *           },
                         *           {
                         *             "id": 2,
                         *             "item": "aliquid",
                         *             "company": "Shanahan LLC",
                         *             "department": "Raqqam",
                         *             "applier": "Ms. Simone Gislason",
                         *             "quantity": 2
                         *           }
                         *         ],
                         *         "notes": "new order for software",
                         *         "status": "rejected",
                         *         "rejection_reason": "hi"
                         *       },
                         *       "message": "تم جلب الطلب بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                created_at: string;
                                order_items: {
                                    id: number;
                                    item: string;
                                    company: string;
                                    department: string;
                                    applier: string;
                                    quantity: number;
                                }[];
                                notes: string;
                                status: string;
                                rejection_reason: string;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Order stats fetched successfully",
                         *       "data": {
                         *         "total": 10,
                         *         "accepted": "4",
                         *         "rejected": "3",
                         *         "pending": "3"
                         *       }
                         *     }
                         */
                        "application/json": {
                            message: string;
                            data: {
                                total: number;
                                accepted: string;
                                rejected: string;
                                pending: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Status
         * @description Role: Accountant
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path: {
                    /** @example 1 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "status": "accepted",
                     *       "rejection_reason": null
                     *     }
                     */
                    "application/json": {
                        status: string;
                        rejection_reason: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": null,
                         *       "message": "تم تحديث حالة الطلب بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: null;
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download PDF */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/pdf */
                    Accept?: string;
                };
                path: {
                    /** @example 1 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role: CTO
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description created,updated,deleted
                     * @example created
                     */
                    "filter[event]"?: string;
                    /** @example 2026-06-02 */
                    "filter[created_at]"?: string;
                    /** @example 50 */
                    paginate?: string;
                    /** @example 1 */
                    page?: string;
                };
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "current_page": 1,
                         *         "data": [
                         *           {
                         *             "id": 3,
                         *             "user_id": 1,
                         *             "user_name": "CTO User",
                         *             "user_role": "CTO",
                         *             "event": "تم إنشاء مستخدم",
                         *             "auditable_type": "مستخدم",
                         *             "auditable_id": 4,
                         *             "created_at": "2026-05-23T12:15:40.000000Z",
                         *             "updated_at": "2026-05-23T12:15:40.000000Z",
                         *             "old_values": [],
                         *             "new_values": {
                         *               "first_name": "John",
                         *               "last_name": "Doe",
                         *               "email": "ypusef@example.com",
                         *               "password": "$2y$12$zeDraoexMrW2EeeYS3pcPe7jQN/37cZ1ApYalFrExGi43JHJGMLmO",
                         *               "department_id": 1,
                         *               "username": "ypusef",
                         *               "id": 4
                         *             }
                         *           },
                         *           {
                         *             "id": 2,
                         *             "user_id": 3,
                         *             "user_name": "IT User",
                         *             "user_role": "IT",
                         *             "event": "تم إنشاء طلب",
                         *             "auditable_type": "طلب",
                         *             "auditable_id": 4,
                         *             "created_at": "2026-05-23T11:59:40.000000Z",
                         *             "updated_at": "2026-05-23T11:59:40.000000Z",
                         *             "old_values": [],
                         *             "new_values": {
                         *               "user_id": 3,
                         *               "status": "pending",
                         *               "id": 4
                         *             }
                         *           },
                         *           {
                         *             "id": 1,
                         *             "user_id": 3,
                         *             "user_name": "IT User",
                         *             "user_role": "IT",
                         *             "event": "تم إنشاء طلب",
                         *             "auditable_type": "طلب",
                         *             "auditable_id": 3,
                         *             "created_at": "2026-05-23T11:43:57.000000Z",
                         *             "updated_at": "2026-05-23T11:43:57.000000Z",
                         *             "old_values": [],
                         *             "new_values": {
                         *               "user_id": 3,
                         *               "status": "pending",
                         *               "id": 3
                         *             }
                         *           }
                         *         ],
                         *         "first_page_url": "http://127.0.0.1:8000/api/audits?page=1",
                         *         "from": 1,
                         *         "last_page": 1,
                         *         "last_page_url": "http://127.0.0.1:8000/api/audits?page=1",
                         *         "links": [
                         *           {
                         *             "url": null,
                         *             "label": "&laquo; Previous",
                         *             "page": null,
                         *             "active": false
                         *           },
                         *           {
                         *             "url": "http://127.0.0.1:8000/api/audits?page=1",
                         *             "label": "1",
                         *             "page": 1,
                         *             "active": true
                         *           },
                         *           {
                         *             "url": null,
                         *             "label": "Next &raquo;",
                         *             "page": null,
                         *             "active": false
                         *           }
                         *         ],
                         *         "next_page_url": null,
                         *         "path": "http://127.0.0.1:8000/api/audits",
                         *         "per_page": 15,
                         *         "prev_page_url": null,
                         *         "to": 3,
                         *         "total": 3
                         *       },
                         *       "message": "تم جلب السجلات بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                current_page: number;
                                data: {
                                    id: number;
                                    user_id: number;
                                    user_name: string;
                                    user_role: string;
                                    event: string;
                                    auditable_type: string;
                                    auditable_id: number;
                                    created_at: string;
                                    updated_at: string;
                                    old_values: string[];
                                    new_values: {
                                        user_id: number;
                                        status: string;
                                        notes: string | null;
                                        id: number;
                                        first_name?: string;
                                        last_name?: string;
                                        username?: string;
                                        password?: string;
                                        department_id?: number;
                                    };
                                }[];
                                first_page_url: string;
                                from: number;
                                last_page: number;
                                last_page_url: string;
                                links: {
                                    url: string | null;
                                    label: string;
                                    page: number | null;
                                    active: boolean;
                                }[];
                                next_page_url: null;
                                path: string;
                                per_page: number;
                                prev_page_url: null;
                                to: number;
                                total: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All
         * @description Role: IT
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 1,
                         *           "name": "Mrs. Virginie Smith"
                         *         },
                         *         {
                         *           "id": 2,
                         *           "name": "Shanel Reynolds"
                         *         },
                         *         {
                         *           "id": 3,
                         *           "name": "Tod Glover"
                         *         },
                         *         {
                         *           "id": 4,
                         *           "name": "Nash Kuhn"
                         *         },
                         *         {
                         *           "id": 5,
                         *           "name": "Laurie Grant"
                         *         },
                         *         {
                         *           "id": 6,
                         *           "name": "Immanuel Lang"
                         *         },
                         *         {
                         *           "id": 7,
                         *           "name": "Alda Dickens Sr."
                         *         },
                         *         {
                         *           "id": 8,
                         *           "name": "Mr. Griffin Wehner"
                         *         },
                         *         {
                         *           "id": 9,
                         *           "name": "Alva Heidenreich"
                         *         },
                         *         {
                         *           "id": 10,
                         *           "name": "Wava Shanahan"
                         *         }
                         *       ],
                         *       "message": "تم جلب المُقدِّمين بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                            }[];
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Store
         * @description Role:IT
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    Accept?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "seham"
                     *     }
                     */
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "name": "seham",
                         *         "updated_at": "2026-05-23T13:17:07.000000Z",
                         *         "created_at": "2026-05-23T13:17:07.000000Z",
                         *         "id": 11
                         *       },
                         *       "message": "تم إنشاء المُقدِّم بنجاح"
                         *     }
                         */
                        "application/json": {
                            data: {
                                name: string;
                                updated_at: string;
                                created_at: string;
                                id: number;
                            };
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
